version: '3'
services:
  datadog-simple-go:
    image: "gcr.io/datadoghq/agent:7.53.0"
    container_name: datadog-simple-go
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOG_LEVEL=INFO
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE="name:datadog-simple-go"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

  simple-go:
    build: app/
    ports:
      - '8000:8000'
    container_name: simple-go
    environment:
      - DD_AGENT_HOST=datadog-simple-go
      - DD_TRACE_DEBUG=false
      - DD_SERVICE=golang-apm-example
      - DD_VERSION=1.0.0
      - DD_ENV=lab
    depends_on:
      - datadog-simple-go
    labels:
      com.datadoghq.tags.service: 'golang-apm-example'
      com.datadoghq.tags.version: '1.0.0'
      com.datadoghq.tags.env: 'lab'  